### PR TITLE
Implement suggested fix for splitChildren prototype

### LINKED ISSUE #9: Removes elements from the DOM
A really beautiful plugin this...

But I'm having a little trouble when applying it to a container which has (so far) 12 children to whom I want shadows to be applied. However, when called, the plugin remove 6 of these children. I couldn't find any mention of this kind of behaviour in the documentation, or an option for specifying the max number of child elements.

So I was wondering... Is this intended behaviour?

I can understand there would be performance issues if there are too many elements, but it might be useful to know that's what's happening. Or even to be able to set the max number of elements.

(I did look through the plugin's JS but couldn't spot where this might be happening. I'd be happy to try and implement an a maxElements option...)

Thanks!

### PR DESCRIPTION
**Pull request by bravokiloecho**
Resolves bigspaceship/shine.js#9
Final solution proposed by @benjaminbojko

### CODE REVIEW

**Comment by benjaminbojko** [comment]
Merged into master and tagged as version [0.2.8](https://github.com/bigspaceship/shine.js/tree/0.2.8). Thanks for your help on this!

**Comment by bravokiloecho** [comment]
You're very welcome! I'm glad I could help and I'm super pleased with how it looks on the site I'm building.

**Comment by benjaminbojko** [comment]
Great to hear that and curious to see the result when it's done!

**Comment by bravokiloecho** [comment]
Hi Benjamin, it's a while since but I've just remembered I was going to show you the result of your code on the site I was building. Well you can see it [here](http://elwyn.co).

Many thanks again for your work on shine.js!

**Comment by benjaminbojko** [comment]
@bravokiloecho Awesome! Glad to see it out in the wild and I love the samples you have, esp. the Beach one :)

**Pull request merged**
